--[[
    Types d'explosion GTA V (eExplosionTag, natives.json officiel).
    class :
      'common'   explosions de gameplay normal (véhicules, grenades, pompes…)
      'flag'     légitimes mais rares/abusées : comptées avec un score faible
      'military' armes militaires/DLC : bloquées sauf Config.Explosions.allowMilitary
      'troll'    sans usage RP, typiques des menus : toujours bloquées
]]

Lists = Lists or {}

Lists.Explosions = {
    [0]  = { 'GRENADE', 'common' },
    [1]  = { 'GRENADELAUNCHER', 'flag' },
    [2]  = { 'STICKYBOMB', 'common' },
    [3]  = { 'MOLOTOV', 'common' },
    [4]  = { 'ROCKET', 'flag' },
    [5]  = { 'TANKSHELL', 'military' },
    [6]  = { 'HI_OCTANE', 'common' },
    [7]  = { 'CAR', 'common' },
    [8]  = { 'PLANE', 'common' },
    [9]  = { 'PETROL_PUMP', 'common' },
    [10] = { 'BIKE', 'common' },
    [11] = { 'DIR_STEAM', 'common' },
    [12] = { 'DIR_FLAME', 'common' },
    [13] = { 'DIR_WATER_HYDRANT', 'common' },
    [14] = { 'DIR_GAS_CANISTER', 'common' },
    [15] = { 'BOAT', 'common' },
    [16] = { 'SHIP_DESTROY', 'common' },
    [17] = { 'TRUCK', 'common' },
    [18] = { 'BULLET', 'common' },
    [19] = { 'SMOKE_GRENADE_LAUNCHER', 'common' },
    [20] = { 'SMOKE_GRENADE', 'common' },
    [21] = { 'BZGAS', 'common' },
    [22] = { 'FLARE', 'common' },
    [23] = { 'GAS_CANISTER', 'common' },
    [24] = { 'EXTINGUISHER', 'common' },
    [25] = { 'PROGRAMMABLEAR', 'military' },
    [26] = { 'TRAIN', 'common' },
    [27] = { 'BARREL', 'common' },
    [28] = { 'PROPANE', 'common' },
    [29] = { 'BLIMP', 'troll' },
    [30] = { 'DIR_FLAME_EXPLODE', 'common' },
    [31] = { 'TANKER', 'common' },
    [32] = { 'PLANE_ROCKET', 'military' },
    [33] = { 'VEHICLE_BULLET', 'military' },
    [34] = { 'GAS_TANK', 'common' },
    [35] = { 'BIRD_CRAP', 'troll' },
    [36] = { 'RAILGUN', 'military' },
    [37] = { 'BLIMP2', 'troll' },
    [38] = { 'FIREWORK', 'flag' },
    [39] = { 'SNOWBALL', 'common' },
    [40] = { 'PROXMINE', 'military' },
    [41] = { 'VALKYRIE_CANNON', 'military' },
    [42] = { 'AIR_DEFENCE', 'military' },
    [43] = { 'PIPEBOMB', 'flag' },
    [44] = { 'VEHICLEMINE', 'military' },
    [45] = { 'EXPLOSIVEAMMO', 'flag' },
    [46] = { 'APCSHELL', 'military' },
    [47] = { 'BOMB_CLUSTER', 'military' },
    [48] = { 'BOMB_GAS', 'military' },
    [49] = { 'BOMB_INCENDIARY', 'military' },
    [50] = { 'BOMB_STANDARD', 'military' },
    [51] = { 'TORPEDO', 'military' },
    [52] = { 'TORPEDO_UNDERWATER', 'military' },
    [53] = { 'BOMBUSHKA_CANNON', 'military' },
    [54] = { 'BOMB_CLUSTER_SECONDARY', 'military' },
    [55] = { 'HUNTER_BARRAGE', 'military' },
    [56] = { 'HUNTER_CANNON', 'military' },
    [57] = { 'ROGUE_CANNON', 'military' },
    [58] = { 'MINE_UNDERWATER', 'military' },
    [59] = { 'ORBITAL_CANNON', 'troll' },
    [60] = { 'BOMB_STANDARD_WIDE', 'military' },
    [61] = { 'EXPLOSIVEAMMO_SHOTGUN', 'flag' },
    [62] = { 'OPPRESSOR2_CANNON', 'military' },
    [63] = { 'MORTAR_KINETIC', 'military' },
    [64] = { 'VEHICLEMINE_KINETIC', 'military' },
    [65] = { 'VEHICLEMINE_EMP', 'military' },
    [66] = { 'VEHICLEMINE_SPIKE', 'military' },
    [67] = { 'VEHICLEMINE_SLICK', 'military' },
    [68] = { 'VEHICLEMINE_TAR', 'military' },
    [69] = { 'SCRIPT_DRONE', 'military' },
    [70] = { 'RAYGUN', 'military' },
    [71] = { 'BURIEDMINE', 'military' },
    [72] = { 'SCRIPT_MISSILE', 'military' },
    [73] = { 'RCTANK_ROCKET', 'military' },
    [74] = { 'BOMB_WATER', 'military' },
    [75] = { 'BOMB_WATER_SECONDARY', 'military' },
    [76] = { 'MINE_CNCSPIKE', 'military' },
    [77] = { 'BZGAS_MK2', 'common' },
    [78] = { 'FLASHGRENADE', 'common' },
    [79] = { 'STUNGRENADE', 'common' },
    [80] = { 'CNC_KINETICRAM', 'military' },
    [81] = { 'SCRIPT_MISSILE_LARGE', 'military' },
    [82] = { 'SUBMARINE_BIG', 'military' },
    [83] = { 'EMPLAUNCHER_EMP', 'military' },
}

-- Explosions "ambiantes" pouvant légitimement naître loin du joueur qui les
-- synchronise (véhicules/objets qu'il possède réseau) : pas de contrôle de distance.
Lists.ExplosionsVehicle = {
    [6] = true, [7] = true, [8] = true, [9] = true, [10] = true, [15] = true, [16] = true, [17] = true,
    [23] = true, [26] = true, [27] = true, [28] = true, [31] = true, [34] = true,
}
